EX-3448 Update Adapter to support video
sovrn/Prebid.js pull request #36
Opened 2021-12-07 15:18 UTC by maximpakhomov

2021-12-07 16:00 UTC, mikhalovich reviewed
@jrosendahl Should we add validation for required fields [here](https://github.com/sovrn/Prebid.js/pull/36/files#diff-47700f8dab978f7908ef5969dd8043b8fde6ee51690e7f80a9d19a387f34ec3bL17)?

2021-12-09 22:53 UTC, jrosendahl requested changes

2021-12-09 22:53 UTC, jrosendahl commented on modules/sovrnBidAdapter.js
> +        if (bid.mediaTypes && bid.mediaTypes.video) {
we need to not support bid.mediaTypes.video.context = 'adpod'

2021-12-09 22:53 UTC, jrosendahl commented on modules/sovrnBidAdapter.js
>              netRevenue: true,
The returned VAST URL or raw VAST XML should be added into bid.vastUrl or bid.vastXml, respectively.

2021-12-09 22:53 UTC, jrosendahl commented on modules/sovrnBidAdapter.js
> +          let bidSizes = bid.mediaTypes.video.playerSize
This could be done better by getting video first (line 87).

2021-12-09 22:53 UTC, jrosendahl commented on modules/sovrnBidAdapter.js
> +          imp.video = {
We should support all of the video parameters 
I really like how this adapter did it https://github.com/prebid/Prebid.js/blob/832c13ee4126ac20a81e00fc35c8d71fa0afff25/modules/deepintentBidAdapter.js
specifically 
https://github.com/prebid/Prebid.js/blob/832c13ee4126ac20a81e00fc35c8d71fa0afff25/modules/deepintentBidAdapter.js#L179

2021-12-09 22:53 UTC, jrosendahl commented on test/spec/modules/sovrnBidAdapter_spec.js
we probably need an interpretresponse test as well

2021-12-09 22:53 UTC, jrosendahl commented on modules/sovrnBidAdapter.js
> -            mediaType: BANNER,
Also for video we are going to not send the nurl, we will have it embedded in the creative.

2021-12-10 03:38 UTC, jrosendahl commented on modules/sovrnBidAdapter.js
>              netRevenue: true,
We only ever will only have VAST XML

2021-12-10 18:27 UTC, jrosendahl requested changes
Looking better, some comments

2021-12-10 18:27 UTC, jrosendahl commented on modules/sovrnBidAdapter.js
> +            bid.ad = decodeURIComponent(sovrnBid.adm)
I am unsure if we want to set ad for video units, we probably want to decodeURI before the regex

2021-12-10 18:27 UTC, jrosendahl commented on modules/sovrnBidAdapter.js
> +            bid.ad = decodeURIComponent(sovrnBid.adm)
And we probably want to have uri decoded data in the VAST XML field

2021-12-10 18:27 UTC, jrosendahl commented on modules/sovrnBidAdapter.js
> +            bid.ad = decodeURIComponent(sovrnBid.adm)
Do we want to rely on a regex or should we reply with the type in our response @cpabst

2021-12-10 18:27 UTC, jrosendahl commented on modules/sovrnBidAdapter.js
> +export const ORTB_VIDEO_PARAMS = {
this probably does not need to be exported

2021-12-14 17:29 UTC, jrosendahl approved these changes
Looks great but Do not submit to prebid until integration tests have been ran.

2022-01-07 20:34 UTC, cpabst approved these changes
Integration tests have been run.

2022-02-01 18:36 UTC, cpabst commented
Close after prebid merge

2022-02-01 18:36 UTC, closed without merging