EX-3637 Prebid should not pass requests without mime types
sovrn/Prebid.js pull request #41
Opened 2022-03-22 11:31 UTC by mikhalovich

2022-03-22 15:03 UTC, cpabst reviewed
A question

2022-03-22 15:03 UTC, cpabst commented on modules/sovrnBidAdapter.js
> +  isBidRequestValid: function c(bid) {
What's going on with these 2 lines?

2022-03-22 19:55 UTC, jrosendahl requested changes
Please see updated ticket

2022-03-23 12:09 UTC, mikhalovich commented on modules/sovrnBidAdapter.js
> +  isBidRequestValid: function c(bid) {
Thanks, Chis. I didn't notice it. I removed it

2022-03-23 13:11 UTC, mikhalovich commented
@jrosendahl Done

2022-03-23 14:16 UTC, cpabst approved these changes
LGTM

2022-04-11 19:45 UTC, jrosendahl approved these changes
lgtm

2022-05-05 10:10 UTC, maximpakhomov commented
@jrosendahl @cpabst if this PR is no longer needed, can it be closed or merged?

2022-05-05 15:22 UTC, cpabst commented
Yes, this should be closed.

2022-05-05 15:22 UTC, closed without merging